using System;
using System.Linq;
using System.Security;
using System.Text;

namespace AdvancedSceneManager.CsProjAttributes
{

    /// <summary>Base class for <see cref="CsProjAttribute"/> that generate <see langword="&lt;PropertyGroup&gt;"/> tags.</summary>
    public abstract class CsProjPropertyAttribute : CsProjAttribute
    {
        public override string parentTag => "PropertyGroup";
    }

    /// <summary>Base class for <see cref="CsProjAttribute"/> that generate <see langword="&lt;ItemGroup&gt;"/> tags.</summary>
    public abstract class CsProjItemAttribute : CsProjAttribute
    {
        public override string parentTag => "ItemGroup";
    }

    /// <summary>
    /// The base attribute for:
    /// <list type="bullet">
    /// <item><see cref="DocumentationFileAttribute"/>.</item>
    /// <item><see cref="SuppressWarningAttribute"/>.</item>
    /// <item><see cref="IncludeAttribute"/>.</item>
    /// <item><see cref="NestFilesAttribute"/>.</item>
    /// </list>
    /// </summary>
    public abstract class CsProjAttribute : Attribute
    {
        protected abstract void GenerateCsProjFragment(CsProjAttribute[] attributes);

        public abstract string parentTag { get; }

        StringBuilder sb;

        public string GetCsProjFragment(CsProjAttribute[] attributes)
        {
            if (string.IsNullOrEmpty(parentTag))
                throw new InvalidOperationException("parentTag must be set.");

            sb = new StringBuilder();

            GenerateCsProjFragment(attributes);

            if (sb.Length == 0)
                return null;

            sb.Insert(0, $"\n<!-- Generated by {GetType().FullName} -->\n<{parentTag}>\n");
            sb.Append($"</{parentTag}>");

            return sb.ToString();
        }

        public void Insert(string tag, params (string name, string value)[] attributes) => Insert(tag, null, attributes);

        public void Insert(string tag, string value = null, params (string name, string value)[] attributes)
        {

            sb.Append("\t<");
            sb.Append(Escape(tag));

            if (attributes.Length > 0)
            {
                sb.Append(' ');
                sb.AppendJoin(" ", attributes.Select(a => $"{Escape(a.name)}=\"{Escape(a.value)}\""));
            }

            if (string.IsNullOrEmpty(value))
                sb.Append(" />");
            else
            {
                sb.Append('>');
                sb.Append(Escape(value));
                sb.Append("</");
                sb.Append(Escape(tag));
                sb.Append(">");
            }

            sb.AppendLine();

        }

        static string Escape(string value) =>
            SecurityElement.Escape(value);

    }

}
